# Generated by Django 2.0.3 on 2018-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkShortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='shortLink',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
