# Generated by Django 2.0.3 on 2018-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkShortener', '0003_linkmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='shortLink',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
