# Generated by Django 2.0.3 on 2018-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkShortener', '0004_auto_20180324_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
