# Generated by Django 2.0.3 on 2018-03-24 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkShortener', '0005_auto_20180324_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.TextField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
