# Generated by Django 2.0.3 on 2018-03-24 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkShortener', '0006_auto_20180324_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
